package compiladores.AST;

public enum NodeType {
    ProgramNode,
    ClassNode,
    MethodNode,
    AttributeNode,
    BlockNode,
    IfNode,
    WhileNode,
    AsigNode,
    ReturnNode,
    ForNode,
    //LlamadaMetodoNode,
    LiteralNode,
    BinaryNode,
    UnaryNode,
    EqualNode,
    NotEqualNode,
    GreaterNode,
    GreaterEqualNode,
    LessNode,
    LessEqualNode,
    AndNode,
    OrNode,
    IdentifierNode,
    MulNode,
    DivNode,
    AddNode,
    SubNode,
    IntegerLiteral,
    FloatLiteral,
    StringLiteral,
    BooleanLiteral,
    VoidTypeNode,
    NilLiteral,
    ArrayAccessNode,
    SelfNode,
    VarNode,
    FieldAccessNode,
    StaticMethodCall,
    MethodCallNode,
    ConstructorCallNode,
    NewNode,
    ArrayCreationNode,
    SimpleSentenceNode

    // Add more node types as needed
}
